image: "ubuntu:19.04"

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LD_LIBRARY_PATH: criterion-v2.3.3/lib
    BREW: criterion-v2.3.3

before_script:
    - apt update -qq && apt install -y -qq clang build-essential wget libblocksruntime-dev
    - wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2
    - tar -xvjf criterion-v2.3.3-linux-x86_64.tar.bz2
    - clang --version
    - which clang

cache:
    paths:
        - obj/*.o
        - libft/obj/*.o

build:
    stage: build
    script:
        - make test
    artifacts:
        paths:
            - test_libft
