image: "ubuntu:19.04"

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - add-apt-repository ppa:snaipewastaken/ppa -y
    - apt update -qq && apt install -y -qq clang build-essential criterion-dev
    - clang --version
    - which clang

cache:
    paths:
        - obj/*.o
        - obj/libft/*.o

build:
    stage: build
    script:
        - make test
    artifacts:
        paths:
            - test_libft
