name: build/test CI

on: [push]

jobs:
    build:
        runs-on: macOS-latest
        steps:
        - name: pull source
          uses: actions/checkout@v1
        - name: install criterion
          run: brew install snaipe/soft/criterion
        - name: run make
          run: make
          env:
              BREW: /usr/local/
        - name: run make test
          run: make test
          env:
              BREW: /usr/local/
