name: build/test CI

on: [push]

jobs:
    build:
        runs-on: macOS-latest
        steps:
        - name: pull source
          uses: actions/checkout@v1
          with:
              submodules: recursive
        - name: install criterion
          run: brew install snaipe/soft/criterion
        - name: compile libft
          run: make
          env:
              BREW: /usr/local/
        - name: test normal libft functions
          run: make test
          env:
              BREW: /usr/local/
        - name: test bonus functions
          run: make test
          env:
              BREW: /usr/local/
